Ported to gtk3 and json
sugarlabs/AnalyzeJournal pull request #9
Opened 2017-12-24 13:30 UTC by sanatankc

closes #6 
closes #7 

It is working for most part. There are not any major problems in logs as I could find.

2017-12-25 21:09 UTC, quozl requested changes
In future you can spot this by reviewing the patch bands of the commit, which is what I did during my review.

2017-12-25 21:09 UTC, quozl commented on utils.py
> +    print(color.get_fill_color())
Did you forget to remove this `print`?

2017-12-26 01:07 UTC, sanatankc commented
Thanks @quozl, I removed print statement and fixed minor bug pointed by @cristian99garcia.

2017-12-26 01:37 UTC, quozl approved these changes

2017-12-26 01:38 UTC, merged